
destination: tokens-dd-seq/dolma-orig-OG-sm
# batch_size: 1000 
documents:
  - /home/ec2-user/dolma-orig-repart/*.gz
seed: 3920
# max_size: 1_000_000_000
processes: 192 
dtype: uint32
tokenizer:
  name_or_path: allenai/dolma2-tokenizer
  bos_token_id: null
  eos_token_id: 100257
  pad_token_id: 100277
  segment_before_tokenization: false
  encode_special_tokens: true
# work_dir:
#   input: tokstmp/input
#   output: tokstmp/output
