streams:
  - name: thread-mix-mmlu-topics-plus
    documents:
      - s3://ai2-llm/pretraining-data/sources/reddit/dolma_raw/merged_versions/merged_qa_all/documents/*.gz
    attributes:
      - taggersec2
      - dedupe_by_text
      - mmlutopics
      - topics
      # - dclmtagtest
      # - dedupe_ngrams_13_1
    output:
      max_size_in_bytes: 1_000_000_000
      path: s3://ai2-llm/pretraining-data/sources/reddit/dolma_raw/merged_versions/merged_qa_all/mixed/thread-mix-mmlu-topics-plus
    filter:
      include:
      - .attributes.mmlutopics__mmlu_subreddit__doc[0][2] > 0.5   
      - .attributes.topics__politics_subreddit__doc[0][2] > 0.5
      - .attributes.topics__history_subreddit__doc[0][2] > 0.5
      - .attributes.topics__science_subreddit__doc[0][2] > 0.5   
      #   - >-
      #     (.attributes.dedupe_ngrams_13_1 | length == 0) or
      #     ((.attributes.dedupe_ngrams_13_1 | map(.[2] * (.[1] - .[0])) | add) / (.text | length) <= 0.3)
      exclude:
        - .attributes.taggersec2__char_length_v1__length[0][2] < 5
        - .attributes.taggersec2__char_length_v1__length[0][2] > 40000
        - .attributes.taggersec2__longest_string__length[0][2] > 2048
        - .attributes.taggersec2__contains_url__doc[0][2] > 0.5
        - .attributes.taggersec2__removed_deleted__doc[0][2] > 0.5
        - .metadata.removed_by_category and .metadata.removed_by_category != null
        - .metadata.over_18 and .metadata.over_18 == true
        - .attributes.taggersec2__banned_subreddit_membership__doc[0][2] > 0.5
        - .attributes.taggersec2__bot_author__doc[0][2] > 0.5
        - .attributes.taggersec2__comment_bot_author__doc[0][2] > 0.5
        - .attributes.taggersec2__starts_nonascii__doc[0][2] > 0.5
        - .attributes.taggersec2__ft_lang_id_en_doc_v2__en[0][2] < 0.5
        - .attributes.taggersec2__tokenizer_repetitions_v2r2__doc_max_score_repetition and .attributes.taggersec2__tokenizer_repetitions_v2r2__doc_max_score_repetition[0][2] >= 15
        - .metadata.url and ((.metadata.url | split("/r/").[1]) != (.metadata.permalink | split("/r/").[1]))
        - .metadata.media == true
        - .attributes.dedupe_by_text and .attributes.dedupe_by_text[0] and .attributes.dedupe_by_text[0][2] > 0.5
        # - .metadata.score < 10
        # - .metadata.comment_scores[0] < 5
      syntax: jq
work_dir:
  input: testmixtmpd/input
  output: testmixtmpd/output
