gantry run \
  --workspace ai2/reddit \
  --priority high \
  --preemptible \
  --beaker-image dirkg/OLMo \
  --cluster ai2/jupiter-cirrascale-2 \
  --gpus 1 \
  --replicas 1 \
  --leader-selection \
  --host-networking \
  --budget ai2/oe-data \
  --no-nfs \
  --venv 'base' \
  --weka oe-training-default:/weka/oe-training-default \
  --env LOG_FILTER_TYPE=local_rank0_only \
  --env R2_PROFILE=R2 \
  --env S3_PROFILE=S3 \
  --env WEKA_PROFILE=WEKA \
  --env-secret AWS_CONFIG=AWS_CONFIG \
  --env-secret AWS_CREDENTIALS=AWS_CREDENTIALS \
  --env-secret R2_ENDPOINT_URL=R2_ENDPOINT_URL \
  --env-secret WEKA_ENDPOINT_URL=WEKA_ENDPOINT_URL \
  --env-secret WANDB_API_KEY=WANDB_API_KEY \
  --shared-memory 10GiB \
  --install "pip install transformers hf_transfer" \
  --yes \
  --timeout=-1 \
  -- python scripts/format-rewriting/qwen_inference.py
