streams:
  - name: merged_qa_all_prefilter
    documents:
      - s3://ai2-llm/pretraining-data/sources/reddit/dolma_raw/merged_versions/merged_qa_all_wsubreddit/documents/*.gz
    attributes:
      - prelim_filters
      - dedupe_by_text
    output:
      max_size_in_bytes: 1_000_000_000
      path: s3://ai2-llm/pretraining-data/sources/reddit/dolma_raw/merged_versions/merged_qa_all_wsubreddit/merged_qa_all_prefilter
    filter:  
      #   - >-
      #     (.attributes.dedupe_ngrams_13_1 | length == 0) or
      #     ((.attributes.dedupe_ngrams_13_1 | map(.[2] * (.[1] - .[0])) | add) / (.text | length) <= 0.3)
      exclude:
        # - .attributes.prelim_filters__char_length_v1__length[0][2] < 5
        # - .attributes.prelim_filters__char_length_v1__length[0][2] > 40000
        # - .attributes.prelim_filters__longest_string__length[0][2] > 2048
        # - .attributes.prelim_filters__contains_url__doc[0][2] > 0.5
        - .attributes.prelim_filters__removed_deleted__doc[0][2] > 0.5
        - .metadata.removed_by_category and .metadata.removed_by_category != null
        - .metadata.over_18 and .metadata.over_18 == true
        - .attributes.prelim_filters__banned_subreddit_membership__doc[0][2] > 0.5
        - .attributes.prelim_filters__bot_author__doc[0][2] > 0.5
        - .attributes.prelim_filters__comment_bot_author__doc[0][2] > 0.5
        # - .attributes.prelim_filters__starts_nonascii__doc[0][2] > 0.5
        # - .attributes.prelim_filters__ft_lang_id_en_doc_v2__en[0][2] < 0.5
        # - .attributes.prelim_filters__tokenizer_repetitions_v2r2__doc_max_score_repetition and .attributes.prelim_filters__tokenizer_repetitions_v2r2__doc_max_score_repetition[0][2] >= 15
        - .metadata.url and ((.metadata.url | split("/r/").[1]) != (.metadata.permalink | split("/r/").[1]))
        - .metadata.media == true
        - .attributes.dedupe_by_text and .attributes.dedupe_by_text[0] and .attributes.dedupe_by_text[0][2] > 0.5
        # - .metadata.score < 10
        # - .metadata.comment_scores[0] < 5
      syntax: jq
work_dir:
  input: mixtmpd/input
  output: mixtmpd/output
